apiVersion: apps/v1
kind: Deployment
metadata:
  name: applocation-deployment
  labels:
    app: noam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: noam
    spec:
      containers:
      - name: app
        image: noamsegevgabay/noam_app:0
        ports:
        - containerPort: 80
